package model

// RegionData address data
func (address *Address) RegionData() map[string]Address {
	return map[string]Address{
		"Seoul": Address{
			"Gangnam-gu",
			"Gangdong-gu",
			"Gangbuk-gu",
			"Gangseo-gu",
			"Gwanak-gu",
			"Gwangjin-gu",
			"Guro-gu",
			"Geumcheon-gu",
			"Nowon-gu",
			"Dobong-gu",
			"Dongdaemun-gu",
			"Dongjak-gu",
			"Mapo-gu",
			"Seodaemun",
			"Seocho-gu",
			"Seongdong-gu",
			"Seongbuk-gu",
			"Songpa-gu",
			"Yangcheon-gu",
			"Yeongdeungpo-gu",
			"Yongsan-gu",
			"Eunpyeong-gu",
			"Jongno-gu",
			"Jung-gu",
			"Jungnang-gu",
		},
		"Gyeonggi": Address{
			"Gapyeong-gun",
			"Deokyang-gu, Goyang-si",
			"Ilsan-dong-gu, Goyang-si",
			"Ilsanseo-gu, Goyang-si",
			"Gwacheon City",
			"Gwangmyeong City",
			"Gwangju City",
			"Guri City",
			"Gunpo City",
			"Gimpo City",
			"Namyangju City",
			"Dongducheon City",
			"Bucheon City",
			"Seongnam-si Bundang-gu",
			"Sungnam-gu, Sujeong-gu",
			"Jungwon-gu, Seongnam-si",
			"Gwonseon-gu, Suwon-si",
			"Yeongtong-gu, Suwon-si",
			"Jangan-gu, Suwon-si",
			"Paldal-gu, Suwon-si",
			"Siheung City",
			"Ansan-si, Danwon-gu",
			"Sangnok-gu, Ansan-si",
			"Anseong City",
			"Dongan-gu, Anyang",
			"Manan-gu, Anyang-si",
			"Yangju City",
			"Yangpyeong-gun",
			"Yeoju City",
			"Yeoncheon-gun",
			"Osan City",
			"Giheung-gu, Yongin-si",
			"Suji-gu, Yongin-si",
			"Chungin-gu, Yongin-si",
			"Uiwang City",
			"Uijeongbu City",
			"Icheon City",
			"Paju City",
			"Pyeongtaek City",
			"Pocheon",
			"Hanam City",
			"Hwaseong City",
		},
		"Incheon": Address{
			"Ganghwa-gun",
			"Gyeyang-gu",
			"Namdong-gu",
			"East Europe",
			"Michuholgu",
			"Bupyeong-gu",
			"Western",
			"Yeonsu-gu",
			"Ongjin-gun",
			"Jung-gu",
		},
		"Gangwon": Address{
			"Gangneung City",
			"Goseong-gun",
			"Donghae City",
			"Samcheok City",
			"Sokcho City",
			"Yanggu-gun",
			"Yangyang-gun",
			"Yeongwol-gun",
			"Wonju City",
			"Inje-gun",
			"Jeonseon-gun",
			"Cheorwon-gun",
			"Chuncheon City",
			"Taebaek City",
			"Pyeongchang-gun",
			"Hongcheon-gun",
			"Hwacheon-gun",
			"Hoengseong-gun",
		},
		"Daejeon": Address{
			"Daedeok-gu",
			"Dong-gu",
			"Seo-gu",
			"Yooseong-gu",
			"Jung-gu",
		},
		"Sejong": Address{
			"Sejong City",
		},
		"Chungnam": Address{
			"Gyeryong City",
			"Princess City",
			"Geumsan-gun",
			"Nonsan City",
			"Dangjin City",
			"Boryeong City",
			"Buyeo-gun",
			"Seosan City",
			"Seocheon-gun",
			"Asan City",
			"Budget",
			"Dongnam-gu, Cheonan-si",
			"Seobuk-gu, Cheonan-si",
			"Cheongyang-gun",
			"Taean-gun",
			"Hongseong-gun",
		},
		"Chungbuk": Address{
			"Goesan-gun",
			"Danyang-gun",
			"Boeun-gun",
			"Yeongdong-gun",
			"Okcheon-gun",
			"Eumseong-gun",
			"Jecheon-si",
			"Jungpyeong-gun",
			"Jincheon-gun",
			"Sangdang-gu Cheongju",
			"Seowon-gu, Cheongju-si",
			"Cheongwon-gu, Cheongju-si",
			"Heungdeok-gu, Cheongju-si",
			"Chungju City",
		},
		"Busan": Address{
			"Gangseo-gu",
			"Geumjeong-gu",
			"Gijanggun",
			"Nam-gu",
			"Dong-gu",
			"Dongnae-gu",
			"Busan Jingu",
			"Buk-gu",
			"Sasang-gu",
			"Saha-gu",
			"Seo-gu",
			"Sooyoung-gu",
			"Yeonje-gu",
			"Youngdo-gu",
			"Jung-gu",
			"Haeundae-gu",
		},
		"Ulsan": Address{
			"Nam-gu",
			"Dong-gu",
			"Buk-gu",
			"Ulju-gun",
			"Jung-gu",
		},
		"Gyeongnam": Address{
			"Geoje City",
			"Geochang-gun",
			"Goseong-gun",
			"Gimhae City",
			"Namhaegun",
			"Milyang City",
			"Sichuan City",
			"Sancheong County",
			"Yangsan City",
			"Uiryeong-gun",
			"Jinju City",
			"Changnyeong-gun",
			"Masanhappo-gu, Changwon-si",
			"Masan Membership District of Changwon City",
			"Seongsan-gu, Changwon-si",
			"Uichang-gu, Changwon-si",
			"Jinhae-gu, Changwon-si",
			"Tongyeong City",
			"Hadong-gun",
			"Haman-gun",
			"Hamyang-gun",
			"Hapcheon-gun",
		},
		"Gyeongbuk": Address{
			"Gyeongsan City",
			"Gyeongju City",
			"Goryeong-gun",
			"Gumi City",
			"Gunwi-gun",
			"Gimcheon City",
			"Mungyeong City",
			"Bonghwa-gun",
			"Sangju City",
			"Seongju-gun",
			"Andong City",
			"Yeongdeok-gun",
			"Yeongyang-gun",
			"Yeongju City",
			"Yeongcheon City",
			"Yecheon-gun",
			"Ulleung-gun",
			"Uljin-gun",
			"Uiseong-gun",
			"Cheongdo-gun",
			"Cheongsong-gun",
			"Chilgok-gun",
			"Nam-gu, Pohang",
			"Buk-gu, Pohang",
		},
		"Dae-gu": Address{
			"Nam-gu",
			"Dalseo-gu",
			"Dalseong-gun",
			"Dong-gu",
			"Buk-gu",
			"Seo-gu",
			"Soosung-gu",
			"Jung-gu",
		},
		"Gwangju": Address{
			"Gwangsan-gu",
			"Nam-gu",
			"Dong-gu",
			"Buk-gu",
			"Seo-gu",
		},
		"Jeonnam": Address{
			"Gangjin-gun",
			"Goheung-gun",
			"Gokseong-gun",
			"Gwangyang City",
			"Gurye-gun",
			"Naju City",
			"Damyang-gun",
			"Mokpo City",
			"Muan County",
			"Boseong-gun",
			"Suncheon City",
			"Shinan-gun",
			"Yeosu City",
			"Yeonggwang-gun",
			"Yeongam-gun",
			"Wando",
			"Jangseong-gun",
			"Jangheung-gun",
			"Jindo-gun",
			"Hampyeong-gun",
			"Haenam-gun",
			"Hwasun-gun",
		},
		"Jeonbuk": Address{
			"Gochang-gun",
			"Gunsan City",
			"Gimje City",
			"Namwon City",
			"Muju-gun",
			"Buan-gun",
			"Sunchang-gun",
			"Wanju-gun",
			"Iksan City",
			"Imsil-gun",
			"Jangsu-gun",
			"Deokjin-gu, Jeonju",
			"Wansan-gu, Jeonju-si",
			"Jungeup-si",
			"Jinan-gun",
		},
		"Jeju": Address{
			"Seogwipo City",
			"Jeju City",
		},
	}
}
