version: "3.7"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    
  mongo:
    image: mongo
    restart: always
    env_file: .env
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env

  localstack:
    image: localstack/localstack
    ports:
      - 4572:4572
    environment:
      - SERVICES=s3
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d
