definitions:
  model.Account:
    properties:
      created_at:
        example: "2019-12-23 12:27:37"
        type: string
      email:
        example: test@gmail.com
        type: string
      gender:
        example: male
        type: string
      id:
        example: 389df385-ccaa-49c1-aee2-698ba1191857
        type: string
      image_url:
        example: profile.image_url.com
        type: string
      interest:
        example: develop
        type: string
      provider:
        type: string
      updated_at:
        example: "2019-12-23 12:27:37"
        type: string
    type: object
  model.Token:
    properties:
      access:
        type: string
      id:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /accounts:
    get:
      consumes:
      - application/json
      parameters:
      - description: account email
        in: query
        name: email
        required: true
        type: string
      - description: account service provider
        in: query
        name: provider
        required: true
        type: string
      - description: account password (email provider only)
        in: query
        name: password
        type: string
      - description: account social_id
        in: query
        name: social_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Token'
      tags:
      - Accounts
    post:
      consumes:
      - multipart/form-data
      description: create account
      parameters:
      - description: account email address
        in: formData
        name: email
        required: true
        type: string
      - description: login service provider
        in: formData
        name: provider
        required: true
        type: string
      - description: user's gender male or female
        in: formData
        name: gender
        required: true
        type: string
      - description: interested part in develop, design, manage
        in: formData
        name: interest
        required: true
        type: string
      - description: socialId when use social login
        in: formData
        name: social_id
        type: string
      - description: need if don't use social login
        in: formData
        name: password
        type: string
      - description: Profile image file
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "201": {}
      tags:
      - Accounts
  /accounts/{id}:
    delete:
      description: delete account by id
      parameters:
      - description: account Id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200": {}
      security:
      - AccessToken: []
      - RefreshToken: []
      tags:
      - Accounts
    get:
      consumes:
      - application/json
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      security:
      - AccessToken: []
      - RefreshToken: []
      tags:
      - Accounts
    put:
      consumes:
      - multipart/form-data
      description: update account
      parameters:
      - description: accountId
        in: path
        name: id
        required: true
        type: string
      - description: account email address
        in: formData
        name: email
        required: true
        type: string
      - description: login service provider
        in: formData
        name: provider
        required: true
        type: string
      - description: user's gender male or female
        in: formData
        name: gender
        required: true
        type: string
      - description: interested part in develop, design, manage
        in: formData
        name: interest
        required: true
        type: string
      - description: socialId when use social login
        in: formData
        name: social_id
        type: string
      - description: need if don't use social login
        in: formData
        name: password
        type: string
      - description: Profile image file
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200": {}
      security:
      - AccessToken: []
      tags:
      - Accounts
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
