definitions:
  dto.Account:
    properties:
      email:
        example: test@gmail.com
        type: string
      file_id:
        example: file_id
        type: string
      gender:
        example: male
        type: string
      interest:
        example: develop
        type: string
      password:
        example: password
        type: string
      provider:
        example: gmail
        type: string
      social_id:
        example: social_id
        type: string
    required:
    - email
    - provider
    type: object
  model.Account:
    properties:
      accessToken:
        example: accesstoken
        type: string
      created_at:
        example: "2019-12-23 12:27:37"
        type: string
      email:
        example: test@gmail.com
        type: string
      gender:
        example: male
        type: string
      id:
        example: 389df385-ccaa-49c1-aee2-698ba1191857
        type: string
      image_url:
        example: profile.image_url.com
        type: string
      interest:
        example: develop
        type: string
      provider:
        type: string
      updated_at:
        example: "2019-12-23 12:27:37"
        type: string
    type: object
  model.File:
    properties:
      account_id:
        example: 389df385-ccaa-49c1-aee2-698ba1191857
        type: string
      created_at:
        example: "2019-12-23 12:27:37"
        type: string
      id:
        example: 389df385-ccaa-49c1-aee2-698ba1191857
        type: string
      image_url:
        example: profile.image_url.com
        type: string
      updated_at:
        example: "2019-12-23 12:27:37"
        type: string
      usage:
        example: profile
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /accounts:
    get:
      consumes:
      - application/json
      parameters:
      - description: account email
        in: query
        name: email
        required: true
        type: string
      - description: account service provider
        in: query
        name: provider
        required: true
        type: string
      - description: account password (email provider only)
        in: query
        name: password
        type: string
      - description: account social_id
        in: query
        name: social_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      tags:
      - Accounts
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: Create Account data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.Account'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Account'
      tags:
      - Accounts
  /accounts/{id}:
    delete:
      description: delete account by id
      parameters:
      - description: account Id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      security:
      - AccessToken: []
      tags:
      - Accounts
    get:
      consumes:
      - application/json
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      security:
      - AccessToken: []
      tags:
      - Accounts
    put:
      consumes:
      - application/json
      description: update account
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      - description: Update Account data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.Account'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      security:
      - AccessToken: []
      tags:
      - Accounts
  /files:
    post:
      consumes:
      - multipart/form-data
      description: create file
      parameters:
      - description: accountId
        in: formData
        name: account_id
        required: true
        type: string
      - description: file usage
        in: formData
        name: usage
        required: true
        type: string
      - description: Profile image file
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "201": {}
      security:
      - AccessToken: []
      tags:
      - Files
  /files/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: file Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.File'
      security:
      - AccessToken: []
      tags:
      - Files
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
