definitions:
  dto.Account:
    type: object
  model.Account:
    properties:
      createdAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
    type: object
  model.Accounts:
    items:
      properties:
        createdAt:
          type: string
        id:
          type: string
        updatedAt:
          type: string
      type: object
    type: array
info:
  contact: {}
  license: {}
paths:
  /accounts:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Accounts'
      tags:
      - Accounts
    post:
      consumes:
      - application/json
      description: create account group
      parameters:
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.Account'
          type: object
      produces:
      - application/json
      responses:
        "200": {}
      tags:
      - Accounts
  /accounts/{id}:
    delete:
      description: delete account by id
      parameters:
      - description: account ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200": {}
      tags:
      - Accounts
    get:
      consumes:
      - application/json
      parameters:
      - description: account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      tags:
      - Accounts
    put:
      consumes:
      - application/json
      description: create account group
      parameters:
      - description: account ID
        in: path
        name: id
        required: true
        type: string
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.Account'
          type: object
      produces:
      - application/json
      responses:
        "200": {}
      tags:
      - Accounts
swagger: "2.0"
